### ISSUE TITLE
Missing instruction in README.md

### ISSUE THREAD

**Issue by helboukkouri** [jgc128/mednli_baseline#2]
Hi,

This is no big deal but maybe there should be a mention to creating the `./data/cache` directory before trying to run the `train.py`script to avoid this kind of errors:

```
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main(cfg)
  File "train.py", line 26, in main
    dataset_train, dataset_dev = get_dataset(cfg)
  File "cloned_repos/mednli_baseline/utils/helpers.py", line 113, in get_dataset
    save_pickle((dataset_train, dataset_dev, dataset_test,), cache_filename)
  File "cloned_repos/mednli_baseline/utils/pickle.py", line 13, in save_pickle
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/cache/dataset_1_50.pkl'
```

**Comment by jgc128** [comment]
Hi,

Thank you, I'll fix this
